### ISSUE TITLE
:art:   Fail Block Redesign: block redesign

### ISSUE THREAD

**Issue by paulkahura** [italanta/elewa#628] opened 2023-09-26 14:26 UTC
## User stories

As a user, I want the "Fail Block" component in the app to be redesigned to enhance its usability and visual appeal.

---

Quick links: [Summary](#summary) | [Description](#description) | [Template](#template) | [Example](#example) | [Resources](#resources)

---

### Technical Description
The current design is: 
![image](https://github.com/italanta/elewa/assets/35740939/45fcc237-88f0-4912-a610-01e1775e73f6)

It should be changed to:
![image](https://github.com/italanta/elewa/assets/35740939/695e97bd-3096-460d-8711-bc6d57bb4343)

The files can be found at `libs/features/convs-mgr/stories/blocks/library/fail-block/`. 

The designs are [here](https://www.figma.com/file/ZGHzSstXOYPMFU1EiqjEHD/Untitled?type=design&node-id=1%3A4&mode=design&t=Hf7DxaUUMQ3BWy57-1)

### Acceptance Criteria

1. The block should look exactly like the designs.
2. Use of `rem`, `em` as opposed to `px`.
3. All changes should be isolated to the following  `libs/features/convs-mgr/stories/blocks/library/fail-block/`.

**Comment by Sanyam-jain30** [comment] 2023-09-26 16:52
I have expertise in it, Can I be please assigned to it?

**Comment by paulkahura** [comment] 2023-09-27 09:32
> I have worked on design changes in previous works also, so can you please assign it to me?

You can do it and create a PR

**Comment by Sanyam-jain30** [comment] 2023-09-30 17:45
Hello @paulkahura I am facing an issue while setting up elewa locally.
While doing npm install I am facing this issue.
When I use the node version of 14.20.1, it is getting struck every time during installation:
![image](https://github.com/italanta/elewa/assets/78720027/8dab951a-0f0d-4350-b9d4-3c94d503b792)

When I shifted to a higher version of the node, I got an npm error:
![image](https://github.com/italanta/elewa/assets/78720027/489eae21-115b-4a49-9bf8-44296b59c8ad)

When I use --force or --legacy-peer-deps again the installation gets stuck in between. Can you please guide me to a successful installation?

**Comment by paulkahura** [comment] 2023-10-02 05:56
> Hello @paulkahura I am facing an issue while setting up elewa locally. While doing npm install I am facing this issue. When I use the node version of 14.20.1, it is getting struck every time during installation: ![image](https://user-images.githubusercontent.com/78720027/271787592-8dab951a-0f0d-4350-b9d4-3c94d503b792.png)
> 
> When I shifted to a higher version of the node, I got an npm error: ![image](https://user-images.githubusercontent.com/78720027/271787630-489eae21-115b-4a49-9bf8-44296b59c8ad.png)
> 
> When I use --force or --legacy-peer-deps again the installation gets stuck in between. Can you please guide me to a successful installation?

Have you gone through the setup md file?

**Comment by Sanyam-jain30** [comment] 2023-10-02 06:01
> Have you gone through the setup md file?
Yes, I have followed all the steps, but while doing the npm install I am facing this issue.

**Comment by paulkahura** [comment] 2023-10-02 08:55
try working with node 16

**Comment by LemmyMwaura** [comment] 2023-10-03 06:17
@Sanyam-jain30 Work with node 16 and then do a clean install with the command `npm i --legacy-peer-deps`. We will update the setup file as it is a bit outdated.

**Comment by Sanyam-jain30** [comment] 2023-10-03 16:38
Okay, I will try it.

**Comment by Sanyam-jain30** [comment] 2023-10-06 10:40
Sorry guys, I have tried npm 16 and also npm LTS, even I have re-cloned the repository three times but the issue is still there on my laptop. Even reinstalling the IDE and Node hasn't worked. I think I wouldn't be able to complete this assigned work.
I am really sorry for this trouble and also for wasting your time. Please allow someone else to solve this issue.
Thank you and once again sorry for this problem.

**Comment by LemmyMwaura** [comment] 2023-10-08 09:30
@Sanyam-jain30 Ok, no worries, we'll assign it to someone else, although the peer dep issue should be solved by this command `npm i --legacy-peer-deps.` Thanks for attempting to work on it. we'll always have issues so you give this a try later.

**Comment by Sanyam-jain30** [comment] 2023-10-08 11:51
Actually it was not working, I have tried peer dep and also force but still the npm install was not able to complete even if I keep it for 5 hours in a good network connection. Trust me I have tried every single possibility before saying no. 
I will sure try to rectify this problem from service center soon and will try to contribute in solving other issues.

**Closed** 2023-10-13 08:55 UTC
Labels: enhancement, good first issue, 1-pointer
